"""Slack Notifier Module - Send AI Daily Brief to Slack channel."""

import os
import requests
from datetime import datetime
from typing import List, Dict


# Slack OAuth Token from .zshenv
SLACK_TOKEN = os.getenv("SLACK_TOKEN")


def get_channel_id(token: str) -> str:
    """Get channel ID from token."""
    response = requests.post(
        "https://slack.com/api/conversations.list",
        headers={"Authorization": f"Bearer {token}"},
        data={"limit": 100}
    )
    data = response.json()
    if data.get("ok"):
        for channel in data.get("channels", []):
            print(f"  - #{channel.get('name')} (ID: {channel.get('id')})")
    return None


def send_to_slack(report: str, analyzed_articles: List[Dict], channel_id: str = None) -> bool:
    """Send report to Slack channel."""
    if not SLACK_TOKEN:
        print("Error: SLACK_TOKEN not set")
        return False

    # Build Slack message blocks
    blocks = build_slack_blocks(analyzed_articles)

    # If no channel specified, try to find #general or first available
    if not channel_id:
        # Use chat.postMessage without channel to see what happens, or ask user to provide channel ID
        channel_id = os.getenv("SLACK_CHANNEL_ID", "#general")

    # Send message
    response = requests.post(
        "https://slack.com/api/chat.postMessage",
        headers={
            "Authorization": f"Bearer {SLACK_TOKEN}",
            "Content-Type": "application/json"
        },
        json={
            "channel": channel_id,
            "text": f"🤖 AI Daily Brief - {datetime.now().strftime('%Y-%m-%d')}",
            "blocks": blocks
        }
    )

    result = response.json()
    if result.get("ok"):
        print(f"✅ Report sent to Slack channel: {channel_id}")
        return True
    else:
        print(f"❌ Slack error: {result.get('error')}")
        return False


def build_slack_blocks(articles: List[Dict]) -> List[Dict]:
    """Build Slack message blocks from analyzed articles."""

    # Header
    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"🤖 AI Daily Brief - {datetime.now().strftime('%d/%m/%Y')}",
                "emoji": True
            }
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"📊 *{len(articles)} bài viết* từ TechCrunch, VentureBeat, MIT Tech Review, Y Combinator"
            }
        },
        {"type": "divider"}
    ]

    # Top 3 Opportunities
    all_opportunities = []
    for article in articles:
        all_opportunities.extend(article.get("opportunities", []))

    # Get unique opportunities
    unique_opps = list(set(all_opportunities))[:3]

    if unique_opps:
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": "*🎯 Top 3 Cơ hội:*\n" + "\n".join([f"• {opp}" for opp in unique_opps])
            }
        })
        blocks.append({"type": "divider"})

    # Top 3 articles (most important)
    top_articles = articles[:3]

    blocks.append({
        "type": "section",
        "text": {
            "type": "mrkdwn",
            "text": "*📰 Tin quan trọng:*"
        }
    })

    for i, article in enumerate(top_articles, 1):
        title = article.get("title", "")[:80]
        summary = article.get("summary", "")[:150]
        url = article.get("url", "")

        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*{i}. {title}*\n{summary}...\n<{url}|Đọc tiếp →>"
            }
        })

    # Actionable recommendation
    if articles and articles[0].get("actionable"):
        blocks.append({"type": "divider"})
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*⚡ Khuyến nghị:*\n{articles[0].get('actionable')}"
            }
        })

    # Footer
    blocks.append({"type": "divider"})
    blocks.append({
        "type": "context",
        "elements": [
            {
                "type": "mrkdwn",
                "text": f"🤖 Generated by AI Daily Brief • {datetime.now().strftime('%H:%M')}"
            }
        ]
    })

    return blocks


def list_channels() -> None:
    """List available channels for the user to choose."""
    if not SLACK_TOKEN:
        print("Error: SLACK_TOKEN not set")
        return

    print("\n📋 Available channels:")
    response = requests.post(
        "https://slack.com/api/conversations.list",
        headers={"Authorization": f"Bearer {SLACK_TOKEN}"},
        data={"limit": 100}
    )
    data = response.json()
    if data.get("ok"):
        for channel in data.get("channels", []):
            print(f"  - #{channel.get('name')} (ID: {channel.get('id')})")
    else:
        print(f"❌ Error: {data.get('error')}")


if __name__ == "__main__":
    # Test
    print("Testing Slack connection...")
    print(f"Token available: {'Yes' if SLACK_TOKEN else 'No'}")

    if SLACK_TOKEN:
        print("\nAvailable channels:")
        list_channels()

    print("\nTo use:")
    print("  export SLACK_TOKEN='xoxe.xoxp-1-...'")
    print("  export SLACK_CHANNEL_ID='C012345678'  # Channel ID (not name)")
